/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "linkedin" | "instagram" | "twitter" | "facebook";
  url?: string;
};

export type Stat = {
  _type: "stat";
  value: string;
  label: string;
};

export type ProductCategory = {
  _type: "productCategory";
  name: string;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  height?: string;
};

export type WorkflowStep = {
  _type: "workflowStep";
  number?: string;
  title: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ValueProp = {
  _type: "valueProp";
  icon?: string;
  title: string;
  subtitle?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type NavLink = {
  _type: "navLink";
  text: string;
  href: string;
  isExternal?: boolean;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainNav?: Array<{
    _key: string;
  } & NavLink>;
  ctaButton?: {
    text?: string;
    href?: string;
  };
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    badge?: string;
    headlineLines?: Array<string>;
    highlightedLine?: string;
    tagline?: string;
    ctaText?: string;
    ctaLink?: string;
    heroImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    heroImageAlt?: string;
    imageCaption?: string;
    badgeText?: string;
  };
  marqueeItems?: Array<string>;
  trustBar?: {
    label?: string;
    partners?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "partner";
    }>;
  };
  valueProps?: {
    title?: string;
    subtitle?: string;
    items?: Array<{
      _key: string;
    } & ValueProp>;
    instructionText?: string;
    ctaText?: string;
  };
  howItWorks?: {
    title?: string;
    subtitle?: string;
    steps?: Array<{
      _key: string;
    } & WorkflowStep>;
  };
  assortment?: {
    title?: string;
    description?: string;
    ctaText?: string;
    ctaLink?: string;
    categories?: Array<{
      _key: string;
    } & ProductCategory>;
  };
  about?: {
    label?: string;
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    imageAlt?: string;
    imageBadge?: {
      value?: string;
      label?: string;
    };
    features?: Array<{
      title?: string;
      description?: string;
      _key: string;
    }>;
    linkText?: string;
    linkHref?: string;
  };
  stats?: Array<{
    _key: string;
  } & Stat>;
  featuredTestimonial?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "testimonial";
  };
  cta?: {
    title?: string;
    subtitle?: string;
    primaryButton?: {
      text?: string;
      href?: string;
    };
    secondaryButton?: {
      text?: string;
      href?: string;
    };
  };
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  authorName: string;
  authorTitle?: string;
  authorCompany?: string;
  authorImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  siteTagline?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoAlt?: string;
  seo?: Seo;
  footer?: {
    address?: string;
    phone?: string;
    email?: string;
    certifications?: Array<string>;
    socialLinks?: Array<{
      _key: string;
    } & SocialLink>;
    sitemapLabel?: string;
    sitemapLinks?: Array<{
      _key: string;
    } & NavLink>;
    legalLabel?: string;
    legalLinks?: Array<{
      _key: string;
    } & NavLink>;
    contactLabel?: string;
    copyrightText?: string;
    locationTag?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes = Seo | SocialLink | Stat | ProductCategory | WorkflowStep | ValueProp | NavLink | Partner | SanityImageCrop | SanityImageHotspot | Navigation | Homepage | Testimonial | SiteSettings | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: homepageQuery
// Query: *[_type == "homepage"][0] {    hero {      badge,      headlineLines,      highlightedLine,      tagline,      ctaText,      ctaLink,      heroImage,      heroImageAlt,      imageCaption,      badgeText    },    marqueeItems,    trustBar {      label,      partners[]-> {        _id,        name,        logo      }    },    valueProps {      title,      subtitle,      items[] {        icon,        title,        subtitle,        description,        image      },      instructionText,      ctaText    },    howItWorks {      title,      subtitle,      steps[] {        number,        title,        description,        image      }    },    assortment {      title,      description,      ctaText,      ctaLink,      categories[] {        name,        image,        height      }    },    about {      label,      title,      description,      image,      imageAlt,      imageBadge,      features[] {        title,        description      },      linkText,      linkHref    },    stats[] {      value,      label    },    featuredTestimonial-> {      quote,      authorName,      authorTitle,      authorCompany,      authorImage    },    cta {      title,      subtitle,      primaryButton,      secondaryButton    },    seo {      metaTitle,      metaDescription,      ogImage    }  }
export type HomepageQueryResult = {
  hero: {
    badge: string | null;
    headlineLines: Array<string> | null;
    highlightedLine: string | null;
    tagline: string | null;
    ctaText: string | null;
    ctaLink: string | null;
    heroImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    heroImageAlt: string | null;
    imageCaption: string | null;
    badgeText: string | null;
  } | null;
  marqueeItems: Array<string> | null;
  trustBar: {
    label: string | null;
    partners: Array<{
      _id: string;
      name: string;
      logo: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  } | null;
  valueProps: {
    title: string | null;
    subtitle: string | null;
    items: Array<{
      icon: string | null;
      title: string;
      subtitle: string | null;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
    instructionText: string | null;
    ctaText: string | null;
  } | null;
  howItWorks: {
    title: string | null;
    subtitle: string | null;
    steps: Array<{
      number: string | null;
      title: string;
      description: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  } | null;
  assortment: {
    title: string | null;
    description: string | null;
    ctaText: string | null;
    ctaLink: string | null;
    categories: Array<{
      name: string;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      height: string | null;
    }> | null;
  } | null;
  about: {
    label: string | null;
    title: string | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageAlt: string | null;
    imageBadge: {
      value?: string;
      label?: string;
    } | null;
    features: Array<{
      title: string | null;
      description: string | null;
    }> | null;
    linkText: string | null;
    linkHref: string | null;
  } | null;
  stats: Array<{
    value: string;
    label: string;
  }> | null;
  featuredTestimonial: {
    quote: string;
    authorName: string;
    authorTitle: string | null;
    authorCompany: string | null;
    authorImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  cta: {
    title: string | null;
    subtitle: string | null;
    primaryButton: {
      text?: string;
      href?: string;
    } | null;
    secondaryButton: {
      text?: string;
      href?: string;
    } | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;
// Variable: navigationQuery
// Query: *[_type == "navigation"][0] {    mainNav[] {      text,      href,      isExternal    },    ctaButton {      text,      href    }  }
export type NavigationQueryResult = {
  mainNav: Array<{
    text: string;
    href: string;
    isExternal: boolean | null;
  }> | null;
  ctaButton: {
    text: string | null;
    href: string | null;
  } | null;
} | null;
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    siteName,    siteTagline,    logo,    logoAlt,    footer {      address,      phone,      email,      certifications,      socialLinks[] {        platform,        url      },      sitemapLabel,      sitemapLinks[] {        text,        href,        isExternal      },      legalLabel,      legalLinks[] {        text,        href,        isExternal      },      contactLabel,      copyrightText,      locationTag    }  }
export type SiteSettingsQueryResult = {
  siteName: string;
  siteTagline: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  logoAlt: string | null;
  footer: {
    address: string | null;
    phone: string | null;
    email: string | null;
    certifications: Array<string> | null;
    socialLinks: Array<{
      platform: "facebook" | "instagram" | "linkedin" | "twitter" | null;
      url: string | null;
    }> | null;
    sitemapLabel: string | null;
    sitemapLinks: Array<{
      text: string;
      href: string;
      isExternal: boolean | null;
    }> | null;
    legalLabel: string | null;
    legalLinks: Array<{
      text: string;
      href: string;
      isExternal: boolean | null;
    }> | null;
    contactLabel: string | null;
    copyrightText: string | null;
    locationTag: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"homepage\"][0] {\n    hero {\n      badge,\n      headlineLines,\n      highlightedLine,\n      tagline,\n      ctaText,\n      ctaLink,\n      heroImage,\n      heroImageAlt,\n      imageCaption,\n      badgeText\n    },\n    marqueeItems,\n    trustBar {\n      label,\n      partners[]-> {\n        _id,\n        name,\n        logo\n      }\n    },\n    valueProps {\n      title,\n      subtitle,\n      items[] {\n        icon,\n        title,\n        subtitle,\n        description,\n        image\n      },\n      instructionText,\n      ctaText\n    },\n    howItWorks {\n      title,\n      subtitle,\n      steps[] {\n        number,\n        title,\n        description,\n        image\n      }\n    },\n    assortment {\n      title,\n      description,\n      ctaText,\n      ctaLink,\n      categories[] {\n        name,\n        image,\n        height\n      }\n    },\n    about {\n      label,\n      title,\n      description,\n      image,\n      imageAlt,\n      imageBadge,\n      features[] {\n        title,\n        description\n      },\n      linkText,\n      linkHref\n    },\n    stats[] {\n      value,\n      label\n    },\n    featuredTestimonial-> {\n      quote,\n      authorName,\n      authorTitle,\n      authorCompany,\n      authorImage\n    },\n    cta {\n      title,\n      subtitle,\n      primaryButton,\n      secondaryButton\n    },\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage\n    }\n  }\n": HomepageQueryResult;
    "\n  *[_type == \"navigation\"][0] {\n    mainNav[] {\n      text,\n      href,\n      isExternal\n    },\n    ctaButton {\n      text,\n      href\n    }\n  }\n": NavigationQueryResult;
    "\n  *[_type == \"siteSettings\"][0] {\n    siteName,\n    siteTagline,\n    logo,\n    logoAlt,\n    footer {\n      address,\n      phone,\n      email,\n      certifications,\n      socialLinks[] {\n        platform,\n        url\n      },\n      sitemapLabel,\n      sitemapLinks[] {\n        text,\n        href,\n        isExternal\n      },\n      legalLabel,\n      legalLinks[] {\n        text,\n        href,\n        isExternal\n      },\n      contactLabel,\n      copyrightText,\n      locationTag\n    }\n  }\n": SiteSettingsQueryResult;
  }
}
